config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :static_pages, only: :index
  root "static_pages#index"
  namespace :admin do
    resources :garages
    resources :static_pages, only: %i(index)
  end
end

app/models/garage.rb
class Garage < ApplicationRecord
  has_many :coaches, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :trips, through: :coaches

  mount_uploader :image, PictureUploader

  validate  :image_size

  scope :search_garage, (lambda do |city_start, city_end, date|
    joins("LEFT JOIN coaches ON garages.id = coaches.garage_id
      LEFT JOIN trips ON coaches.id = trips.coach_id")
    .where("trips.city_start LIKE ? AND trips.city_finish LIKE ? AND trips.time_start between ? and ?",
      "%#{city_start}%", "%#{city_end}%", "#{date.to_s} 00:00:00",
      "#{date.end_of_day}")
    .group("garages.id")
  end)

  private

  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "should be less than 5MB")
    end
  end
end

app/controllers/admin/garages_controller.rb
module Admin
  class GaragesController < Admin::BaseController
    def index
      @title = "Nhà xe"
      @garages = Garage.all
    end

    def new; end
  end
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
  before_action :check_datetime, :downcase_params, only: :index

  def index
    @garages = Garage.search_garage params[:city_start], params[:city_end],
      Date.parse(params[:time_start])
    @trips = Trip.search_trip params[:city_start], params[:city_end],
      params[:time_start]
    @customer = Customer.new
    @customer.tickets.new
    store_location

    return if @garages
    flash.now["success"] = t".no_garage"
    render :index
  end

  

  private

  def downcase_params
    params[:city_start].downcase!
    params[:city_end].downcase!
  end


  def check_datetime
    return if params[:time_start].present?
    flash[:danger] = t ".insert_date"
    redirect_to root_url
  end
end

app/helpers/garages_helper.rb
module GaragesHelper
  def check_seat seat, trip
    ticket = seat.tickets.find_by trip_id: trip.id
    if ticket.nil? || ticket.status_cancel?
      "available"
    else 
      "unavailable"
    end
  end

  def list_start_point trip
    trip.stop_points.collect { |p| [ p.bus_station.name ] }
  end
end

app/views/admin/garages/_form.html.erb
<%= form_for [:admin, garage], html: {class: "form-horizontal form-label-left" } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :name, class: "form-control col-md-7 col-xs-12", required: "required" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :phone_number, class: "form-control col-md-7 col-xs-12", required: "required" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :address, class: "form-control col-md-7 col-xs-12" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :info, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= f.text_field :info, class: "form-control col-md-7 col-xs-12" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <span class="picture">
        <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
    </div>
  </div>
  <div class="ln_solid"></div>
  <div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <button class="btn btn-primary" type="reset">Reset</button>
      <%= f.submit yield(:button_text), class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/admin/garages/edit.html.erb
<% provide :button_text, "Submit" %>
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Form Elements</h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Form Design <small>different form elements</small></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a></li>
            <li><a href="#">Settings 2</a></li>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <br>
      <%= render "form", garage: @garage %>
      <form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">

      </form>
    </div>
  </div>
</div>
  </div>
</div>

app/views/admin/garages/index.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= @title %> <small>  <strong></strong></small></h3>
    </div>
  </div>
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Danh sách <%= @title %> <small></small></h2>
        <%= link_to new_admin_garage_path, class: "btn btn-primary pull-right", style: "margin-right: 5px;" do %>
        <i class="fa fa-plus"></i> Thêm mới
        <% end %>
        <div class="clearfix"></div>
      </div>
      <div class="x_content" style="display: block;">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th> Tên </th>
              <th> Ảnh </th>
              <th> Số điện thoại </th>
              <th> Địa chỉ </th>
              <th> Thông tin </th>
              <th> Edit </th>
              <th> Delete </th>
            </tr>
          </thead>
          <tbody>
            <% if @garages.any? %>
            <% @garages.each do |gara| %>
            <tr>
              <td> <%= gara.name %> </td>
              <td> <%= gara.image %> </td>
              <td> <%= gara.phone_number %> </td>
              <td> <%= gara.address %> </td>
              <td> <%= gara.info %> </td>
              <td>
                <%= link_to "Edit", "#", class: "edit" %>
              </td>
              <td>
                <%= link_to "Delete", "#", class: "delete" %>
              </td>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/garages/new.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Form Elements</h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Form Design <small>different form elements</small></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a></li>
            <li><a href="#">Settings 2</a></li>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a></li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <br>

      <form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">
        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">First Name <span class="required">*</span>
          </label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Last Name <span class="required">*</span>
          </label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" id="last-name" name="last-name" required="required" class="form-control col-md-7 col-xs-12">
          </div>
        </div>
        <div class="form-group">
          <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Middle Name / Initial</label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="middle-name" class="form-control col-md-7 col-xs-12" type="text" name="middle-name">
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12">Gender</label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <div id="gender" class="btn-group" data-toggle="buttons">
              <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="gender" value="male" data-parsley-multiple="gender"> &nbsp; Male &nbsp;
              </label>
              <label class="btn btn-primary" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
              <input type="radio" name="gender" value="female" data-parsley-multiple="gender"> Female
              </label>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12">Date Of Birth <span class="required">*</span>
          </label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="birthday" class="date-picker form-control col-md-7 col-xs-12" required="required" type="text">
          </div>
        </div>
        <div class="ln_solid"></div>
        <div class="form-group">
          <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button class="btn btn-primary" type="button">Cancel</button>
            <button class="btn btn-primary" type="reset">Reset</button>
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
  </div>
</div>