config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :static_pages, only: :index
  root "static_pages#index"
  namespace :admin do
    resources :garages
    resources :static_pages, only: %i(index)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus_station.rb
class BusStation < ApplicationRecord
  belongs_to :city
  has_many :stop_points, dependent: :destroy
end

app/models/city.rb
class City < ApplicationRecord
  has_many :districts, dependent: :destroy
  has_many :bus_stations, dependent: :destroy
end

app/models/coach.rb
class Coach < ApplicationRecord
  belongs_to :garage
  has_many :trips, dependent: :destroy
  has_many :seats, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :tickets

  accepts_nested_attributes_for :tickets

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true
  validates :phone_number, presence: true
  validates :email, format: {with: VALID_EMAIL_REGEX}, allow_blank: true

  before_save :downcase_email

  private

  def downcase_email
    email.downcase! if email.present?
  end
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
  has_many :bus_stations, dependent: :destroy
end

app/models/garage.rb
class Garage < ApplicationRecord
  has_many :coaches, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :trips, through: :coaches

  mount_uploader :image, PictureUploader

  validate  :image_size

  scope :search_garage, (lambda do |city_start, city_end, date|
    joins("LEFT JOIN coaches ON garages.id = coaches.garage_id
      LEFT JOIN trips ON coaches.id = trips.coach_id")
    .where("trips.city_start LIKE ? AND trips.city_finish LIKE ? AND trips.time_start between ? and ?",
      "%#{city_start}%", "%#{city_end}%", "#{date.to_s} 00:00:00",
      "#{date.end_of_day}")
    .group("garages.id")
  end)

  private

  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "should be less than 5MB")
    end
  end
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :coach
  has_many :tickets

  enum types: {one: 1, two: 2}, _prefix: :types
end

app/models/stop_point.rb
class StopPoint < ApplicationRecord
  enum type: {start: 0, end: 1}

  belongs_to :trip
  belongs_to :bus_station
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :customer
  belongs_to :trip
  belongs_to :seat

  TICKET_PARAMS = %i(id trip_id bus_stop seat_id status).freeze

  after_create :create_code

  enum status: {cancel: 0, paid: 1, pending: 2}, _prefix: :status

  scope :sorted, ->{order created_at: :desc}
  scope :join_customer, ->{joins :customer}
  scope :search_ticket, (lambda do |code, phone_number|
    if code
      where("tickets.code = ?", code).where("customers.phone_number = ?", phone_number)
    else
      where("customers.phone_number = ?", phone_number)
    end
  end)

  private

  def create_code
    update code: SecureRandom.alphanumeric(8).upcase.to_s
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :coach
  has_many :stop_points, dependent: :destroy
  has_many :tickets, dependent: :destroy

  before_save :dowcase_atributes

  self.skip_time_zone_conversion_for_attributes = [:time_start, :time_finish]

  scope :search_trip, (lambda do |city_start, city_end, date|
    joins("LEFT JOIN coaches ON trips.coach_id = coaches.id")
    .where("trips.city_start = '#{city_start}' and trips.city_finish =
      '#{city_end}' and trips.time_start between ? and ?",
      date.to_date.beginning_of_day.strftime("%Y-%m-%d %H:%M:%S"),
      date.to_date.end_of_day.strftime("%Y-%m-%d %H:%M:%S"))
  end)

  private

  def dowcase_atributes
    %w(city_start city_finish).map do |p|
      (send p.to_s).downcase!
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :garage

  has_secure_password
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def create
    check_customer_exist
  end

  def update; end

  private

  def check_customer_exist
    @customer = Customer.find_by(phone_number: params[:customer][:phone_number])

    if @customer.present?
      @tickets = []
      @id_tickets = []
      params[:customer][:tickets_attributes].each do |p|
        @ticket = @customer.tickets.create trip_id: p[1][:trip_id], 
          seat_id: p[1][:seat_id]
        @id_tickets << @ticket.id
        @tickets << @ticket
      end
      render "tickets/pay"
    else
      @customer = Customer.new customer_params

      if @customer.save
        @tickets = @customer.tickets
        @id_tickets = @tickets.ids
        render "tickets/pay"
      else
        flash[:danger] = t ".full_information"
        redirect_back_or @customer
      end
    end
  end

  def customer_params
    params.require(:customer).permit :name, :phone_number, :email,
      tickets_attributes: Ticket::TICKET_PARAMS
  end
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
  before_action :check_datetime, :downcase_params, only: :index

  def index
    @garages = Garage.search_garage params[:city_start], params[:city_end],
      Date.parse(params[:time_start])
    @trips = Trip.search_trip params[:city_start], params[:city_end],
      params[:time_start]
    @customer = Customer.new
    @customer.tickets.new
    store_location

    return if @garages
    flash.now["success"] = t".no_garage"
    render :index
  end

  

  private

  def downcase_params
    params[:city_start].downcase!
    params[:city_end].downcase!
  end


  def check_datetime
    return if params[:time_start].present?
    flash[:danger] = t ".insert_date"
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase

    if user&.authenticate(params[:session][:password])
      log_in user
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".invalid"
    end
    redirect_to root_url
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    if params[:search] == :cancel.to_s
      search_ticket
    elsif params[:search] == :search.to_s
      search_all_tickets
    end
  end

  def new; end

  def edit; end

  def update
    if params[:status] == "cancel"
      @ticket = find_ticket params[:id]

      @ticket.status_cancel! 

      flash.now[:danger] = t ".cancel_fail" unless @ticket.status_cancel?
      redirect_to request.referrer
    elsif params[:status] == "paid"
      @tickets = []
      params[:id_tickets].split.each do |id|
        @ticket = find_ticket id
        @ticket.status_paid! if @ticket.status_pending?
        @tickets << @ticket
      end

      if @ticket.customer.email.present?
        CustomerMailer.customer_email(@ticket.customer, @tickets).deliver_now
      end
      render "tickets/after_pay"
    end
  end

  private

  def find_ticket id
    @ticket = Ticket.find_by id: id
  end

  def search_ticket
    return unless params[:code].present? && params[:phone_number].present?
    @ticket = Ticket.join_customer.search_ticket(params[:code],
      params[:phone_number]).first

    flash.now[:danger] = t ".not_phone_ticket" unless @ticket
  end

  def search_all_tickets
    return unless params[:phone_number].present?
    @tickets = Ticket.join_customer
      .search_ticket(nil, params[:phone_number]).sorted

    flash.now[:danger] = t ".not_phone" if @tickets.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/garages_helper.rb
module GaragesHelper
  def check_seat seat, trip
    ticket = seat.tickets.find_by trip_id: trip.id
    if ticket.nil? || ticket.status_cancel?
      "available"
    else 
      "unavailable"
    end
  end

  def list_start_point trip
    trip.stop_points.collect { |p| [ p.bus_station.name ] }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-5">
  <div class="top-footer d-flex justify-content-between flex-wrap mx-auto">
    <div class=" width-arc-footer">
      <div class="d-flex">
        <%= link_to root_url, class: "mx-auto" do %>
          <%= image_tag "car.png", class: "img-car mt-5"%>
        <% end %>
      </div>
      <p class="p-footer text-justify text-white font-p2-footer mt-3 text-center">Vì một
 Việt Nam không phải xếp hàng mua vé, Hãy chia sẻ rộng rãi về chúng tôi</p>
    </div>
    <div class="width-arc-footer">
      <div class="d2-footer">
        <nav class="nav-footer float-left">
          <a href="#" class="text-white font-weight-bold font-p1-footer mt-3">Useful links</a>
          <ul class="mt-4 text-white">
            <li><p class="text-white font-p2-footer">Home</p></li>
            <li><p class="text-white font-p2-footer">How it works</p></li>
            <li><p class="text-white font-p2-footer">Terms and conditions</p></li>
            <li><p class="text-white font-p2-footer">Cookies policy</p></li>
            <li><p class="text-white font-p2-footer">Contac Us</p></li>
            <li><p class="text-white font-p2-footer">About us</p></li>
            <li><p class="text-white font-p2-footer">Features</p></li>
            <li><p class="text-white font-p2-footer">Event list</p></li>
          </ul>
        </nav>
        <nav class="nav-footer float-right">
          <a href="#" class="text-white font-weight-bold font-p1-footer mt-3">My account</a>
          <ul class="mt-4">
            <li><p class="text-white font-p2-footer">New account</p></li>
            <li><p class="text-white font-p2-footer">Open a account</p></li>
            <li><p class="text-white font-p2-footer">Manage</p></li>
            <li><p class="text-white font-p2-footer">Change password</p></li>
            <li><p class="text-white font-p2-footer">Delete account</p></li>
            <li><p class="text-white font-p2-footer">Dashboard</p></li>
          </ul>	
        </nav>		
      </div>
    </div>
    <div class=" width-arc-footer">
      <div class="d3-footer mx-auto">
        <p class="font-p1-footer text-white font-p1-footer text-center">Chin cảm ơn!</p>
        <div class="icon-footer d-flex justify-content-between mt-4">
          <%= image_tag "Socia1.png" %>
          <%= image_tag "socia2.png" %>
          <%= image_tag "socia3.png" %>
          <%= image_tag "socia4.png" %>
        </div>
        <p class="text-white text-center mt-4">Subscribe to our newsletter</p>
        <div class="shadow-footer mt-1"></div>
      </div>
    </div>
  </div>	
</footer>

app/views/layouts/_footer_admin.html.erb
<div class="pull-right">
Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
</div>
<div class="clearfix"></div>

app/views/layouts/_header.html.erb
<header class="colorbg-dark text-white size-header">
  <div class="container size-header" >
    <div class="float-right d-flex">
      <p class="mr-3"><%= t ".hotline"%></p>
      <p class="mr-3"><%= t ".email" %></p>
      <% if logged_in? %>
        <%= link_to t(".log_out"), logout_path, method: :delete%>
      <% else %>
        <%= link_to t(".log_in"), "", data: { toggle: "modal", target: "#exampleModalCenter" }%>
      <% end %>
      <%= link_to url_for(locale: :vi) do %>
        <%= image_tag "vi.png"%>
      <% end %>
      <%= link_to url_for(locale: :en) do %>
        <%= image_tag "en.png"%>
      <% end %>
    </div>
  </div>
</header>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header contaier-fluid">
        <%= form_with scope: :session, url: login_path, local: true, html: {class: "container-fluid"} do |f| %>
          
          <%= f.label :email, class: "h6 mt-4" %>
          <%= f.email_field :email, class: "form-control bg-text" %>

          <%= f.label :password, class: "h6 mt-4" %>
          <%= f.password_field :password, class: "form-control" %>

          <%= f.submit t(".log_in"), class: "btn colorbg-red form-control mt-4 mb-4 text-body " %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<section class="size-section-1 colorbg-red text-white">
  <div class="container size-section-1 d-flex">
    <div class="d-flex justify-content-start with-50">
      <%= link_to root_url do %>
        <%= image_tag "car.png", class: "img-car"%>
      <% end %>
      <%= link_to t(".buy_ticket"), root_url, class: "txt-section-1 text-white font-weight-bold ml-5"%>
    </div>
    <div class="d-flex justify-content-end with-50">
    <%= link_to t(".find_ticket"), tickets_path(search: "search"), class: "txt-section-1 text-white font-weight-bold ml-4"%>
    <%= link_to t(".ticket_cance"), tickets_path(search: "cancel"), class: "txt-section-1 text-white font-weight-bold ml-4"%>
    <%= link_to t(".garage"), "#", class: "txt-section-1 text-white font-weight-bold ml-4"%>
    </div>
    <div></div>
  </div>
</section>

app/views/layouts/_header_admin.html.erb
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <img src="images/img.jpg" alt="">John Doe
          <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Profile</a></li>
            <li>
              <a href="javascript:;">
              <span class="badge bg-red pull-right">50%</span>
              <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>
            <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
          </ul>
        </li>
        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-envelope-o"></i>
          <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
              <span class="image"><img src="images/img.jpg" alt="Profile Image"></span>
              <span>
              <span>John Smith</span>
              <span class="time">3 mins ago</span>
              </span>
              <span class="message">
              Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
              </a>
            </li>
            <li>
              <a>
              <span class="image"><img src="images/img.jpg" alt="Profile Image"></span>
              <span>
              <span>John Smith</span>
              <span class="time">3 mins ago</span>
              </span>
              <span class="message">
              Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
              </a>
            </li>
            <li>
              <a>
              <span class="image"><img src="images/img.jpg" alt="Profile Image"></span>
              <span>
              <span>John Smith</span>
              <span class="time">3 mins ago</span>
              </span>
              <span class="message">
              Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
              </a>
            </li>
            <li>
              <a>
              <span class="image"><img src="images/img.jpg" alt="Profile Image"></span>
              <span>
              <span>John Smith</span>
              <span class="time">3 mins ago</span>
              </span>
              <span class="message">
              Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                <strong>See All Alerts</strong>
                <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Ticket Fair!</span></a>
    </div>
    <div class="clearfix"></div>
    <div class="profile clearfix">
      <div class="profile_pic">
        <img src="images/img.jpg" alt="..." class="img-circle profile_img">
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2>John Doe</h2>
      </div>
    </div>
    <br>
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
          <li>
            <a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="index.html">Dashboard</a></li>
              <li><a href="index2.html">Dashboard2</a></li>
              <li><a href="index3.html">Dashboard3</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="menu_section">
        <h3>Features</h3>
        <ul class="nav side-menu">
          <li>
            <%= link_to admin_garages_path do %>
            <i class="fa fa-table"></i> Nhà xe
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="sidebar-footer hidden-small">
      <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="" data-original-title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="" data-original-title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="" href="login.html" data-original-title="Logout">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
      </a>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>admin</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "admin", "data-turbolinks-track": "reload" %>
  </head>
<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <%= render "layouts/sidebar" %>
      <%= render "layouts/header_admin" %>
      <div class="right_col" role="main" style="min-height: 774px;">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
        <%= yield %>
      </div>
      <footer>
        <%= render "layouts/footer_admin" %>
      </footer>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabRubyOe15TicketFair</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class = "height-index">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/seat_forms/_seat_form.html.erb
<% if coach.seat_form == 2 %>
  <div class="seatWrap">
    <div class="seats">
      <p class="lower-new">
        <span class="txt-l"><%= t ".t2" %></span>
      </p>
      <ul>
        <% seats.types_two.each do |seat| %>
          <% status = check_seat seat, trip %>
          <li class="seat sleeper <%= status %> "  data="<%= seat.code %>" type="1">
            <a class="seatpick-<%= status %>" data-status="<%= status %>" 
              data-trip="<%= trip.id %>" data-bus-station=" " data-fare="<%= trip.fare %>"
              data-code="<%= seat.code %>" data-id="<%= seat.id %>">
              <span class="seatNo"><%= seat.code %></span></a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
<div class="seatWrap">
  <div class="seats">
    <p class="lower-new">
      <span class="txt-l"><%= t ".t1" %></span>
    </p>
    <p class="lower-driver"><span class="icon2 txt-2"></span></p>
    <ul>
      <% seats.types_one.each do |seat| %>
        <% status = check_seat seat, trip %>
        <li class="seat sleeper <%= status %> "  data="<%= seat.code %>" type="1">
          <a class="seatpick-<%= status %>" data-status="<%= status %>" 
            data-trip="<%= trip.id %>" data-bus-station=" " data-fare="<%= trip.fare %>"
            data-code="<%= seat.code %>" data-id="<%= seat.id %>">
            <span class="seatNo"><%= seat.code %></span></a>
        </li>
      <% end %>
    </ul>
    </ul>
  </div>
</div>

app/views/shared/_form_search.html.erb
<div id="dvSearchTicket" class="ticket-search-filter">
  <div class="container desktop-route-search hidden-xs hidden-sm">
    <%= form_with url: garages_path, local: true, method: :get, html: {class: "form-inline"} do |form| %>
      <div class="form-group">
        <span role="status" aria-live="polite" class="ui-helper-hidden-accessible"></span>
        <%= form.text_field :city_start, class: "location-search startPoint", html: {"data-url": "/static_pages"}, value: params[:city_start] %>
      </div>
      <div class="form-group hidden-xs">
        <p href="#" class="switchButton">⇌</p>
      </div>
      <div class="form-group">
        <span role="status" aria-live="polite" class="ui-helper-hidden-accessible"></span>
        <%= form.text_field :city_end, class: "location-search startPoint", html: {"data-url": "/static_pages"}, value: params[:city_end] %>
      </div>
      <div class="form-group departDate-fg">
        <%= form.text_field :time_start, class: "form-control date date-picker datePicker readonly", value: params[:time_start], "data-date-format"=>"dd-mm-yyyy", "data-date-start-date"=>"+0d", required: true, onkeypress: "return false;" %>
        <div class="form-group quick-date-select fr hidden-xs hidden-sm">
        </div>
      </div>
      <div class="form-group pull-right">
        <%= form.submit "Tìm vé xe", class: "submit-btn btn  search-btn", id: "searchSubmit" %>
      </div>
    <% end %>
  </div>
</div>